stages:
  - test
  - prebuild
  - build
  - deploy

image: zolotoykod/build-tools:latest

lint:
  stage: test
  image: node:alpine
  before_script:
    - apk add --no-cache make bash git
  script:
    - make lint
  cache:
    paths:
      - node_modules

frontend:
  stage: prebuild
  image: node:alpine
  before_script:
    - apk add --no-cache make bash
  script:
    - make frontend
  cache:
    paths:
      - public/node_modules
      - public/.awcache
  artifacts:
    paths:
      - public/dist
  only:
    - tags
    - master

build:
  stage: build
  script:
    - make build
  only:
    - tags
    - master

staging:
  stage: deploy
  script:
    - make deploy
  tags:
    - swarm-deploy
  environment:
    name: staging
    url: http://$CI_ENVIRONMENT_SLUG.$CI_PROJECT_PATH_SLUG.swarm.zolotoykod.ru
  only:
    - master

production:
  stage: deploy
  script:
    - make deploy
  tags:
    - swarm-deploy
  environment:
    name: production
    url: http://$CI_ENVIRONMENT_SLUG.$CI_PROJECT_PATH_SLUG.swarm.zolotoykod.ru
  only:
    - tags
